import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'

import Navbar from "@/component/Navbar"
import UserContext from '@/component/UserContext'
import { GetNotification } from '@/util/data'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export interface UserContextTypes{user_id: string, user_name: string}

const RootLayout = async ({children}: {children: React.ReactNode})=> {
  const notif = await GetNotification()
  return (
    <html lang="en">
      <UserContext>
        <body className={font.className}>
          <Navbar {...{notif}} />
          {children}
        </body>
      </UserContext>
    </html>
  )
}

export default RootLayout
